default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: ws-booking-api_development

test:
  <<: *default
  database: ws-booking-api_test

production:
  <<: *default
  database: ws-booking-api_production

