default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= DB_USER %>
  password: <%= DB_PASSWORD %>

development:
  <<: *default
  database: ws-booking-api_development

test:
  <<: *default
  database: ws-booking-api_test

production:
  <<: *default
  database: ws-booking-api_production

